
all: 
	gcc -o IPv4_stream_socket_server IPv4_stream_socket_server.c
	gcc -o IPv4_stream_socket_client IPv4_stream_socket_client.c

	gcc -o IPv4_datagram_socket_server IPv4_datagram_socket_server.c
	gcc -o IPv4_datagram_socket_client IPv4_datagram_socket_client.c

	gcc -o Unix_stream_socket_server Unix_stream_socket_server.c
	gcc -o Unix_stream_socket_client Unix_stream_socket_client.c

	gcc -o Unix_datagram_socket_server Unix_datagram_socket_server.c
	gcc -o Unix_datagram_socket_client Unix_datagram_socket_client.c

clean:
	rm -rf IPv4_stream_socket_server
	rm -rf IPv4_stream_socket_client
	rm -rf IPv4_datagram_socket_server
	rm -rf IPv4_datagram_socket_client
	rm -rf Unix_stream_socket_server
	rm -rf Unix_stream_socket_client
	rm -rf Unix_datagram_socket_server
	rm -rf Unix_datagram_socket_client
	

